name: Docker Image CI - mapme-spatial-dev
on:
  workflow_dispatch: null
  schedule:
    - cron: "0 4 * * *"
  push:
    paths: ['dockerfiles/mapme-spatial-dev.Dockerfile', '.github/workflows/docker-mapme-spatial-dev.yml', 'scripts/install_sysdeps.sh', 'scripts/install_rspatial_dev.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mapme-initiative/mapme-docker'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (mapme-spatial-dev) Docker image
        if: github.repository == 'mapme-initiative/mapme-docker'
        run: docker build -f dockerfiles/mapme-spatial-dev.Dockerfile . --tag ghcr.io/mapme-initiative/mapme-spatial-dev:1.0
      - name: Publish (mapme-spatial-dev)
        if: github.repository == 'mapme-initiative/mapme-docker'
        run: docker push ghcr.io/mapme-initiative/mapme-spatial-dev:1.0
