name: Docker Image CI - mapme-spatial
on:
  workflow_dispatch: null
  schedule:
    - cron: '0 0,8 * * *'
  push:
    paths: ['dockerfiles/mapme-spatial.Dockerfile', '.github/workflows/docker-mapme-spatial.yml', 'scripts/install_sysdeps.sh', 'scripts/install_rspatial.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mapme-initiative/mapme-docker'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (mapme-spatial) Docker image
        if: github.repository == 'mapme-initiative/mapme-docker'
        run: docker build -f dockerfiles/mapme-spatial.Dockerfile . --tag ghcr.io/mapme-initiative/mapme-spatial:1.0
      - name: Publish (mapme-spatial)
        if: github.repository == 'mapme-initiative/mapme-docker'
        run: docker push ghcr.io/mapme-initiative/mapme-spatial:1.0
